var words=[
    "10-code",
    "2,3-diphosphoglycerate (2,3-DPG)",
    "Abandonment",
    "ABCs",
    "Abduction",
    "Aberrant conduction",
    "ABO blood groups",
    "Abortion",
    "Abrasion",
    "Abruptio placentae",
    "Absence seizure",
    "Absolute refractory period",
    "Acceleration",
    "Acclimatization",
    "Acetylcholinesterase (AChE)",
    "Acid",
    "Acidosis",
    "Acquired immunity",
    "Acrocyanosis",
    "Action potential",
    "Activated charcoal",
    "Active immunity",
    "Active listening",
    "Active rescue zone",
    "Active transport",
    "Actual damages",
    "Acuity",
    "Acute arterial occlusion",
    "Acute coronary syndrome (ACS)",
    "Acute effects",
    "Acute gastroenteritis",
    "Acute pulmonary embolism",
    "Acute renal failure (ARF)",
    "Acute respiratory distress syndrome (ARDS)",
    "Acute retinal artery occlusion",
    "Acute tubular necrosis",
    "Addendum",
    "Addiction",
    "Addison's disease",
    "Addisonian crisis",
    "Adduction",
    "Adenosine triphosphate (ATP)",
    "Adhesion",
    "Adjunct medication",
    "Administration tubing",
    "Administrative law",
    "Adrenergic",
    "Adrenocorticotropic hormone",
    "Adult respiratory distress syndrome (ARDS)",
    "Advance directive",
    "ACLS",
    "Advanced life support (ALS)",
    "Aerobic metabolism",
    "Aeromedical evacuations",
    "Affect",
    "Afferent",
    "Affinity",
    "Afterbirth",
    "Afterload",
    "Against medical advice (AMA)",
    "Ageism",
    "Aggregate",
    "Agonist",
    "Agonist-antagonist (partial agonist)",
    "AIDS",
    "Air embolism",
    "Airbags",
    "Airborne",
    "Air-purifying respirator (APR)",
    "Albumin",
    "Aldosterone",
    "Algorithm",
    "Alkali",
    "Alkalosis",
    "Allergen",
    "Allergic reaction",
    "Allergy",
    "Allied health professions",
    "Alpha radiation",
    "Alveoli",
    "Alzheimer's disease",
    "Amniotic fluid",
    "Amniotic sac",
    "Ampere",
    "Amphiarthrosis",
    "Ampule",
    "Amputation",
    "Amyotrophic lateral sclerosis (ALS)",
    "Anabolism",
    "Anaerobic",
    "Anaerobic metabolism",
    "Analgesia",
    "Analgesic",
    "Anaphylactic shock",
    "Anaphylaxis",
    "Anastomosis",
    "Anatomy",
    "Anchor time",
    "Anemia",
    "Anesthesia",
    "Anesthetic",
    "Aneurysm",
    "Anger",
    "Angina pectoris",
    "Angioneurotic edema",
    "Angiotensin",
    "Anion",
    "Antihyperlipidemic",
    "Anorexia nervosa",
    "Anoxia",
    "Anoxic hypoxemia",
    "Antacid",
    "Antagonist",
    "Antepartum",
    "Anterior cord syndrome",
    "Anterior medial fissure",
    "Anterograde amnesia",
    "Antibiotic",
    "Antibody",
    "Anticoagulant",
    "Antidiuresis",
    "Antidiuretic hormone (ADH)",
    "Antidote",
    "Antidysrhythmic",
    "Antiemetic",
    "Antigen",
    "Antigen processing",
    "Antigen-antibody complex",
    "Antigen-presenting cells (APCs)",
    "Antihistamine",
    "Antihypertensive",
    "Antineoplastic agent",
    "Antiplatelet",
    "Antiseptic",
    "Antitussive",
    "Anuria",
    "Anxiety",
    "Anxious avoidant attachment",
    "Anxious resistant attachment",
    "Aortic dissection",
    "APGAR scoring",
    "Aphasia",
    "Apnea",
    "Apneustic respiration",
    "Apoptosis",
    "Appendicitis",
    "Appendicular skeleton",
    "Aqueous humor",
    "Arachnoid membrane",
    "ARDS",
    "Arrhythmia",
    "Arterial gas embolism (AGE)",
    "Arteries",
    "Arteriosclerosis",
    "Arthritis",
    "Articular surface",
    "Artifact",
    "Ascending loop of Henle",
    "Ascending reticular activating system",
    "Ascending tracts",
    "Ascites",
    "Asepsis",
    "Asphyxia",
    "Aspiration",
    "Assault",
    "Assay",
    "Asthma",
    "Ataxic respiration",
    "Atelectasis",
    "Atherosclerosis",
    "Atrophy",
    "Augmented limb leads",
    "Aural medication",
    "Auscultation",
    "Authoritarian",
    "Authoritative",
    "Autoimmune disease",
    "Autoimmunity",
    "Automatic Collision Notification (ACN) system",
    "Automaticity",
    "Autonomic dysfunction",
    "Autonomic ganglia",
    "Autonomic hyperreflexia syndrome",
    "Autonomic nervous system",
    "Autonomic neuropathy",
    "Autonomy",
    "Autoregulation",
    "Avulsion",
    "Axial loading",
    "Axial skeleton",
    "Axon",
    "B-lymphocytes",
    "Babinski's response",
    "Bacteria",
    "Bacterial tracheitis",
    "Bactericidal",
    "Bacteriostatic",
    "Bag-valve mask",
    "Ballistics",
    "Baroreceptor",
    "Barotrauma",
    "Basal metabolic rate (BMR)",
    "Basic life support (BLS)",
    "Basophil",
    "Battery",
    "Battle's sign",
    "Behavior",
    "Behavioral emergency",
    "Bell's palsy",
    "Bend fractures",
    "Beneficence",
    "Benign prostatic hypertrophy",
    "Bereavement",
    "Beta radiation",
    "Bilateral periorbital ecchymosis",
    "Bioassay",
    "Bioavailability",
    "Bioequivalence",
    "Biologic half-life",
    "Biological agents",
    "Biological/organic",
    "Biotoxin",
    "Biotransformation",
    "BiPAP",
    "Bipolar disorder",
    "Bipolar limb leads",
    "Birth injury",
    "Blast wind",
    "Blepharospasm",
    "Blood pressure",
    "Blood spatter evidence",
    "Blood tube",
    "Blood tubing",
    "Bloodborne",
    "Blood-brain barrier",
    "Blunt trauma",
    "Body armor",
    "Body substance isolation (BSI)",
    "Body surface area (BSA)",
    "Bohr effect",
    "Bolus",
    "Bonding",
    "Borborygmi",
    "Bowel obstruction",
    "Bowman's capsule",
    "Bradycardia",
    "Bradypnea",
    "Brain abscess",
    "Brain ischemia",
    "Brainstem",
    "Branches",
    "Breach of duty",
    "Bronchi",
    "Bronchiectasis",
    "Bronchiolitis",
    "Bronchophony",
    "Broselow tape",
    "Brown-Séquard syndrome",
    "Brudzinki's sign",
    "Bruit",
    "Bubble sheet",
    "Buccal",
    "Buckle fractures",
    "Buffer",
    "Bulimia nervosa",
    "Bundle branch block",
    "Bundle of Kent",
    "Burette chamber",
    "Burnout",
    "Bursa",
    "Bursitis",
    "Calcaneus",
    "Caliber",
    "Callus",
    "CAMEO®",
    "Cancellous",
    "Cannula",
    "Capillary",
    "Capnography",
    "Carbon dioxide",
    "Cardiac arrest",
    "Cardiac contractile force",
    "Cardiac cycle",
    "Cardiac depolarization",
    "Cardiac monitor",
    "Cardiac output",
    "Cardiac tamponade",
    "Cardioacceleratory center",
    "Cardiogenic shock",
    "Cardio inhibitory center",
    "Cardiovascular disease (CVD)",
    "Carina",
    "Carpal bones",
    "Carrier mediated diffusion",
    "Cartilage",
    "Cascade",
    "Catabolism",
    "Cataracts",
    "Catatonia",
    "Catecholamines",
    "Catheter inserted through the needle (intracatheter)",
    "Cation",
    "Cavitation",
    "Cell",
    "Cell membrane",
    "Cell-mediated immunity",
    "Cellular immunity",
    "Cellular swelling",
    "Cellular telephone system",
    "Cellulitis",
    "Central cord syndrome",
    "Central IV line",
    "Central nervous system (CNS)",
    "Central neurogenic hyperventilation",
    "Central pain syndrome",
    "Central venous access",
    "Cerebellum",
    "Cerebral perfusion pressure",
    "Cerebrospinal fluid",
    "Cerebrum",
    "Certification",
    "C-FLOP",
    "Chain of evidence",
    "Chancroid",
    "Chemoreceptor",
    "Chemotactic factors",
    "Chemotaxis",
    "Cheyne-Stokes respiration",
    "Chief complaint",
    "Child abuse",
    "Chlamydia",
    "Choanal atresia",
    "Cholinergic",
    "Chronic gastroenteritis",
    "Chronic obstructive pulmonary disease (COPD)",
    "Chronic renal failure",
    "Chronotropy",
    "Chime",
    "Circadian rhythms",
    "Circulation assessment",
    "Circulatory overload",
    "Circumcision",
    "Circumduction",
    "Cirrhosis",
    "Civil law",
    "Claudication",
    "Clavicle",
    "Cleaning",
    "Cleft lip",
    "Cleft palate",
    "Clinical judgment",
    "Clonal diversity",
    "Clonal selection",
    "Clonic phase",
    "Closed fracture",
    "Closed incident",
    "Closed questions",
    "Closed stance",
    "Closed-ended questions",
    "Clotting",
    "Coagulation",
    "Coagulation necrosis",
    "Coagulation system",
    "Cold zone",
    "Colic",
    "Collagen",
    "Collecting duct",
    "Colloids",
    "Colostomy",
    "Coma",
    "Command",
    "Command Post (CP)",
    "Command Staff",
    "Comminuted fracture",
    "Common law",
    "Communicable",
    "Communicable period",
    "Communication",
    "Community-acquired infection",
    "Comorbidity",
    "Compartment syndrome",
    "Compensated shock",
    "Compensatory pause",
    "Competent",
    "Competitive antagonism",
    "Complement system",
    "Complex partial seizure",
    "Compliance",
    "Concealment",
    "Concentration",
    "Concussion",
    "Conductive deafness",
    "Conductivity",
    "Confidentiality",
    "Confusion",
    "Congenital",
    "Congestive heart failure (CHF)",
    "Congregate care",
    "Conjunctiva",
    "Connective tissue",
    "Consensual reactivity",
    "Consensus standards",
    "Consent",
    "Constitutional law",
    "Contamination",
    "Continuous quality improvement (CQI)",
    "CONTOMS",
    "Contractility",
    "Contraction",
    "Contrecoup injury",
    "Contusion",
    "Convection",
    "Conventional reasoning",
    "Convergent",
    "Cor pulmonale",
    "Core temperature",
    "Cornea",
    "Coronary heart disease (CHD)",
    "Cortex",
    "Cortisol",
    "Coup injury",
    "Coupling interval",
    "Cover",
    "CPAP",
    "Crackles",
    "Cramping",
    "Cranial nerves",
    "Cranium",
    "Creatinine",
    "Crepitation",
    "Crepitus",
    "Cribbing",
    "Cricothyroid membrane",
    "Cricothyrostomy",
    "Cricothyrotomy",
    "Criminal law",
    "Critical thinking",
    "Crohn's disease",
    "Croup",
    "Crowning",
    "Crumple zone",
    "Crush injury",
    "Crush points",
    "Crush syndrome",
    "Crystalloids",
    "Cullen's sign",
    "Cultural imposition",
    "Current",
    "Current of injury (injury current)",
    "Cushing's reflex",
    "Cushing's syndrome",
    "Cushing's triad",
    "Cyanosis",
    "Cystic medial necrosis",
    "Cystitis",
    "Cytochrome oxidase",
    "Cytokines",
    "Cytoplasm",
    "Cytotoxic",
    "Deafness",
    "Debridement",
    "Deceleration",
    "Decerebrate",
    "Decerebrate posture",
    "Decode",
    "Decompensated shock",
    "Decompression illness",
    "Decontaminate",
    "Decontamination",
    "Decorticate",
    "Decorticate posture",
    "Deep frostbite",
    "Deep venous thrombosis",
    "Defamation",
    "Defibrillation",
    "Degenerative neurological disorders",
    "Degloving injury",
    "Degranulation",
    "Dehydration",
    "Delayed effects",
    "Delayed hypersensitivity reaction",
    "DeLee suction trap",
    "Delirium",
    "Delirium tremens (DTs)",
    "Delusions",
    "Demand valve device",
    "Dementia",
    "Demobilized",
    "Demographic",
    "Demylenation",
    "Denature",
    "Depersonalization",
    "Deployment",
    "Depression",
    "Dermatomes",
    "Dermis",
    "Descending loop of Henle",
    "Descending tracts",
    "Desired dose",
    "Detailed physical exam",
    "Devascularization",
    "Diabetes insipidus",
    "Diabetes mellitus",
    "Diabetic ketoacidosis",
    "Diabetic retinopathy",
    "Dialysate",
    "Diapedesis",
    "Diaphoresis",
    "Diaphragmatic hernia",
    "Diaphysis",
    "Diarthrosis",
    "Diastole",
    "Diastolic blood pressure",
    "Diencephalon",
    "Differential field diagnosis",
    "Difficult child",
    "Diffuse axonal injury",
    "Diffusion",
    "Digestive tract",
    "Digital communications",
    "Dilation",
    "Diplopia",
    "Direct pressure",
    "Dirty bomb",
    "Disaster management",
    "Disease period",
    "Disentanglement",
    "Disinfect",
    "Disinfectant",
    "Disinfecting",
    "Dislocation",
    "Dissecting aortic aneurysm",
    "Disseminated intravascular coagulation (DIC)",
    "Dissociate",
    "Dissociative disorder",
    "Distal tubule",
    "Distributive shock",
    "Diuresis",
    "Diuretic",
    "Divergent",
    "Diverticula",
    "Diverticulitis",
    "Diverticulosis",
    "Do Not Resuscitate (DNR) order",
    "Domestic elder abuse",
    "Dosage on hand",
    "Dose packaging",
    "Dosimeter",
    "Down time",
    "Down-regulation",
    "Drag",
    "Drip chamber",
    "Drip rate",
    "Dromotropy",
    "Drop former",
    "Drowning",
    "Drug",
    "Drug overdose",
    "Drug-response relationship",
    "Ductus arteriosus",
    "Due regard",
    "Duplex",
    "Dura mater",
    "Duration of action",
    "Duty to act",
    "Dynamic steady state",
    "Dysmenorrhea",
    "Dysphagia",
    "Dysphoria",
    "Dysplasia",
    "Dyspnea",
    "Dysrhythmia",
    "Dystonias",
    "Dysuria",
    "Easy child",
    "Ecchymosis",
    "Echo procedure",
    "Ectopic beat",
    "Ectopic focus",
    "Ectopic pregnancy",
    "Edema",
    "Effacement",
    "Efferent",
    "Efficacy",
    "Egophony",
    "Einthoven's triangle",
    "Ejection fraction",
    "Elderly",
    "Electrical alternans",
    "Electrocardiogram (ECG)",
    "Electrolyte",
    "Emboli",
    "Embolus",
    "Emergency medical dispatcher (EMD)",
    "Emergency medical services (EMS)",
    "Emergency Operations Center (EOC)",
    "Emergent phase",
    "Emesis",
    "Empathy",
    "EMS Communications Officer",
    "EMT-Tacticals (EMT-Ts)",
    "Encephalitis",
    "Encode",
    "Endocrine gland",
    "Endometriosis",
    "Endometritis",
    "Endometrium",
    "Endotoxins",
    "End-stage renal failure",
    "End-tidal carbon dioxide (ETCO2) detector",
    "Enema",
    "Energy",
    "Enteral route",
    "Enterotoxin",
    "Enucleation",
    "Environmental emergency",
    "Eosinophils",
    "Epicardium",
    "Epidemiology",
    "Epidermis",
    "Epididymis",
    "Epidural hematoma",
    "Epiglottitis",
    "Epiphyseal fracture",
    "Epiphyseal plate",
    "Epiphysis",
    "Epistaxis",
    "Epithelial tissue",
    "Epithelialization",
    "Erythema",
    "Erythrocytes",
    "Erythropoiesis",
    "Erythropoietin",
    "Esophageal Tracheal CombiTube",
    "Esophageal varices",
    "Esophageal varix",
    "Essential equipment",
    "Estimated date of confinement (EDC)",
    "Ethics",
    "Ethnocentrism",
    "ETT",
    "Eustachian tube",
    "Evaporation",
    "Evisceration",
    "Excitability",
    "Exertional metabolic rate",
    "Exocrine",
    "Exocrine gland",
    "Exotoxins",
    "Expectorant",
    "Explosives",
    "Exposure",
    "Expressed consent",
    "Exsanguination",
    "Extension tubing",
    "Extracellular fluid (ECF)",
    "Extrapyramidal symptoms (EPS)",
    "Extrauterine",
    "Extravasation",
    "Extravascular",
    "Extravascular space",
    "Extrication",
    "Extubation",
    "Exudate",
    "Facilitated diffusion",
    "Facilities Unit",
    "Factitious disorder",
    "Fallout",
    "False imprisonment",
    "Fascia",
    "Fasciculations",
    "Fasciculus",
    "Fatigue",
    "Fatigue fracture",
    "Fatty change",
    "Fear",
    "Febrile seizures",
    "Fecal-oral route",
    "Feedback",
    "Femur",
    "Fibrin",
    "Fibrinolysis",
    "Fibrinolytic",
    "Fibroblasts",
    "Fibrosis",
    "Fibula",
    "Field diagnosis",
    "Filtrate",
    "Filtration",
    "FiO2",
    "First-pass effect",
    "Flail chest",
    "Flanks",
    "Flat affect",
    "Fluid shift phase",
    "Focused history and physical exam",
    "Food poisoning",
    "Foreign body airway obstruction (FBAO)",
    "Free drug availability",
    "French",
    "Frostbite",
    "Fugue state",
    "Full thickness burn",
    "Functional impairment",
    "Fungus",
    "Gag reflex",
    "Galea aponeurotica",
    "Gamma radiation",
    "Gangrene",
    "Gastric lavage",
    "Gastroenteritis",
    "Gauge",
    "Geiger counter",
    "General adaptation syndrome (GAS)",
    "General impression",
    "Generalized seizures",
    "Genital warts",
    "Genitourinary system",
    "Geriatric abuse",
    "Geriatrics",
    "Gerontology",
    "Glasgow Coma Scale (GCS)",
    "Glaucoma",
    "Glomerular filtration",
    "Glomerular filtration rate (GFR)",
    "Glomerulonephritis",
    "Glomerulus",
    "Glottic function",
    "Glottis",
    "Glucagon",
    "Glucocorticoids",
    "Glucometer",
    "Gluconeogenesis",
    "Glucose intolerance",
    "Glycogen",
    "Glycogenolysis",
    "Glycolysis",
    "Glycosuria",
    "Gold standard",
    "Golden Hour",
    "Gonorrhea",
    "Good Samaritan laws",
    "Gout",
    "Gram stain",
    "Granulation",
    "Granulocytes",
    "Granuloma",
    "Graves' disease",
    "Gray",
    "Gray matter",
    "Great vessels",
    "Greenstick fractures",
    "Grey Turner's sign",
    "Growth hormone",
    "Growth plate",
    "Gtts",
    "Guarding",
    "Guillain-Barré syndrome",
    "Gynecology",
    "Hairline fracture",
    "Half-life",
    "Hallucinations",
    "Hantavirus",
    "Haptens",
    "Hate crimes",
    "Haversian canals",
    "Hazardous material (hazmats)",
    "Health care professionals",
    "Heart failure",
    "Heat cramps",
    "Heat exhaustion",
    "Heat illness",
    "Heatstroke",
    "HEENT",
    "Hematemesis",
    "Hematochezia",
    "Hematocrit",
    "Hematology",
    "Hematoma",
    "Hematopoiesis",
    "Hematuria",
    "Hemoconcentration",
    "Hemodialysis",
    "Hemoglobin",
    "Hemoglobin-based oxygen-carrying solutions (HBOCs)",
    "Hemolysis",
    "Hemophilia",
    "Hemopneumothorax",
    "Hemoptysis",
    "Hemorrhage",
    "Hemorrhoid",
    "Hemostasis",
    "Hemothorax",
    "Heparin lock",
    "Hepatic alteration",
    "Hepatitis",
    "Hepatomegaly",
    "Hernia",
    "Herniation",
    "Herpes simplex virus",
    "Herpes zoster",
    "Hiatal hernia",
    "High-pressure regulator",
    "Hilum",
    "Histamine",
    "HIV",
    "HLA antigens",
    "Hollow-needle catheter",
    "Homeostasis",
    "Hookworm",
    "Hormone",
    "Hospice",
    "Hot zone",
    "Huber needle",
    "Human immunodeficiency virus (HIV)",
    "Humerus",
    "Humoral immunity",
    "Hydrolysis",
    "Hydrostatic pressure",
    "Hymenoptera",
    "Hyperbaric oxygen chamber",
    "Hyperbilirubinemia",
    "Hypercarbia",
    "Hyperglycemia",
    "Hyperglycemic hyperosmolar nonketotic (HHNK) coma",
    "Hypermetabolic phase",
    "Hyperosmolar",
    "Hyperplasia",
    "Hypersensitivity",
    "Hypertension",
    "Hypertensive emergency",
    "Hypertensive encephalopathy",
    "Hyperthermia",
    "Hyperthyroidism",
    "Hypertonic",
    "Hypertrophy",
    "Hyphema",
    "Hypnosis",
    "Hypochondriasis",
    "Hypodermic needle",
    "Hypoglycemia",
    "Hypoglycemic seizure",
    "Hypo-osmolar",
    "Hypoperfusion",
    "Hypotension",
    "Hypothalamus",
    "Hypothermia",
    "Hypothyroidism",
    "Hypotonic",
    "Hypoventilation",
    "Hypovolemia",
    "Hypovolemic shock",
    "Hypoxemia",
    "Hypoxia",
    "Hypoxic drive",
    "Iliac crest",
    "Ilium",
    "Immediate hypersensitivity reaction",
    "Immune response",
    "Immune senescence",
    "Immune system",
    "Immunity",
    "Immunogens",
    "Immunoglobulin (Ig)",
    "Impacted fracture",
    "Impaled object",
    "Impetigo",
    "Implied consent",
    "Impulse control disorder",
    "Impulsive",
    "Incendiary",
    "Incendiary agents",
    "Incident Command System (ICS)",
    "Incident Commander (IC)",
    "Incision",
    "Incontinence",
    "Incubation period",
    "Index case",
    "Index of suspicion",
    "Induced active immunity",
    "Inertia",
    "Infarction",
    "Infection",
    "Infectious disease",
    "Infestation",
    "Inflammation",
    "Inflammatory process",
    "Influenza",
    "Information Officer (IO)",
    "Informed consent",
    "Infusion",
    "Infusion controller",
    "Infusion pump",
    "Ingestion",
    "Inhalation",
    "Initial assessment",
    "Injection",
    "Injury",
    "Injury risk",
    "Injury-surveillance program",
    "Innominate",
    "Inotropy",
    "Insertion",
    "Inspection",
    "Institutional elder abuse",
    "Insufflate",
    "Insulin",
    "Integumentary system",
    "Intercalated discs",
    "Intermittent claudication",
    "Intermittent mandatory ventilation (IMV)",
    "Interpolated beat",
    "Interstitial fluid",
    "Interstitial nephritis",
    "Interstitial space",
    "Intervener physician",
    "Intervertebral disk",
    "Intracellular fluid (ICF)",
    "Intracerebral hemorrhage",
    "Intracranial pressure (ICP)",
    "Intractable",
    "Intradermal",
    "Intramuscular",
    "Intraosseous",
    "Intrapartum",
    "Intrarenal abscess",
    "Intravascular fluid",
    "Intravascular space",
    "Intravenous access (cannulation)",
    "Intravenous fluid",
    "Intubation",
    "Intussusception",
    "Involuntary consent",
    "Ion",
    "Ionization",
    "Ionize",
    "Ionizing radiation",
    "Iris",
    "Irreversible antagonism",
    "Irreversible shock",
    "Ischemia",
    "Ischial tuberosity",
    "Ischium",
    "Isoimmunity",
    "Isolette",
    "Isometric exercise",
    "Isosthenuria",
    "Isotonic",
    "Isotonic exercise",
    "J wave",
    "Jargon",
    "Joint",
    "Joule's law",
    "Justice",
    "Keloid",
    "Kernig's sign",
    "Ketone bodies",
    "Ketosis",
    "Kidney",
    "Kinetic energy",
    "Kinetics",
    "Kinin system",
    "Korotkoff's sounds",
    "Korsakoff's psychosis",
    "Krebs cycle",
    "Kussmaul's respiration",
    "Kyphosis",
    "Labor",
    "Labrynthitis",
    "Laceration",
    "Lacrimal fluid",
    "Lactic acid",
    "Laminae",
    "Laryngoscope",
    "Larynx",
    "Latent period",
    "Laxative",
    "Le Fort criteria",
    "Leading questions",
    "Legislative law",
    "Lesion",
    "Leukemia",
    "Leukocytes",
    "Leukocytosis",
    "Leukopenia",
    "Leukopoiesis",
    "Leukotrienes",
    "Liability",
    "Liaison Officer (LO)",
    "Libel",
    "Lice",
    "Licensure",
    "Life expectancy",
    "Life-care community",
    "Ligament of Treitz",
    "Ligaments",
    "Ligamentum arteriosum",
    "Liquefaction necrosis",
    "Living will",
    "Local",
    "Local effects",
    "Lock-out/tag-out",
    "Logistics Section",
    "Lower gastrointestinal bleeding",
    "Luer sampling needle",
    "Luer-Lok",
    "Lumen",
    "Lyme disease",
    "Lymph",
    "Lymphangitis",
    "Lymphatic system",
    "Lymphocyte",
    "Lymphokine",
    "Lymphoma",
    "Maceration",
    "Macrodrip tubing",
    "Macrophages",
    "Magill forceps",
    "Major basic protein (MBP)",
    "Major histocompatibility complex (MHC)",
    "Major trauma patient",
    "Malfeasance",
    "Malleolus",
    "Mallory-Weiss tear",
    "Mammalian diving reflex",
    "Mandible",
    "Manic",
    "Manometer",
    "Marfan syndrome",
    "Margination",
    "Mark I kit",
    "Mask",
    "Mass",
    "Mast cells",
    "Material safety data sheets (MSDS)",
    "Maturation",
    "Maxilla",
    "Maximum life span",
    "McBurney point",
    "Measles",
    "Measured volume administration set",
    "Mechanism of injury",
    "Meconium",
    "Medical direction",
    "Medical director",
    "Medical Supply Unit",
    "Medically clean",
    "Medicated solution",
    "Medication injection port",
    "Medications/drugs",
    "Medulla",
    "Medulla oblongata",
    "Medullary canal",
    "Melena",
    "Memory cells",
    "Menarche",
    "Meniere's disease",
    "Meninges",
    "Meningitis",
    "Meningomyelocele",
    "Menopause",
    "Menorrhagia",
    "Menstruation",
    "Mental status",
    "Mental status examination (MSE)",
    "Mesencephalon",
    "Mesenteric infarct",
    "Mesentery",
    "Metabolic acidosis",
    "Metabolic alkalosis",
    "Metabolism",
    "Metacarpals",
    "Metaphysis",
    "Metaplasia",
    "Metatarsal",
    "Metered dose inhaler",
    "Microangiopathy",
    "Microcirculation",
    "Microdrip tubing",
    "Midbrain",
    "Minimum effective concentration",
    "Minimum standards",
    "Minor",
    "Minute volume",
    "Miosis",
    "Miscarriage",
    "Misfeasance",
    "Mitosis",
    "Mittelschmerz",
    "Mobile data terminal",
    "Modeling",
    "Monoclonal antibody",
    "Monocytes",
    "Monokine",
    "Mononucleosis",
    "Mood disorder",
    "Morals",
    "Morgue",
    "Morgue Officer",
    "Moro reflex",
    "Motion",
    "Mucolytic",
    "Mucous membrane",
    "Mucus",
    "Multiple casualty incident (MCI)",
    "Multiple myeloma",
    "Multiple organ dysfunction syndrome (MODS)",
    "Multiple personality disorder",
    "Multiple sclerosis",
    "Multiplex",
    "Mumps",
    "Murphy's sign",
    "Muscle",
    "Muscle tissue",
    "Muscular dystrophy",
    "Mutual aid",
    "Myasthenia gravis",
    "Myocardial infarction (MI)",
    "Myocardial injury",
    "Myocardial ischemia",
    "Myocardium",
    "Myoclonus",
    "Myometrium",
    "Myotome",
    "Myxedema",
    "Myxedema coma",
    "Nares",
    "Nasal cannula",
    "Nasal flaring",
    "Nasal medication",
    "Nasogastric tube/orogastric tube",
    "Nasolacrimal ducts",
    "Nasopharyngeal airway",
    "Nasotracheal route",
    "National Incident Management System (NIMS)",
    "National Emergency Crisis and Disasters Management Authority (NCEMA)",
    "Natural immunity",
    "Naturally acquired immunity",
    "Nature of the illness (NOI)",
    "Near-drowning",
    "Nebulizer",
    "Necrosis",
    "Needle adapter",
    "Needle cricothyrotomy",
    "Negative feedback",
    "Negative feedback loop",
    "Negligence",
    "Neonatal abstinence syndrome (NAS)",
    "Neonate",
    "Neoplasm",
    "Neovascularization",
    "Nephrology",
    "Nephron",
    "Nerve agents",
    "Nerve tissue",
    "Net filtration",
    "Neuroeffector junction",
    "Neurogenic shock",
    "Neuroleptanesthesia",
    "Neuroleptic",
    "Neuron",
    "Neurotransmitter",
    "Neutron radiation",
    "Neutropenia",
    "Neutropenic",
    "Neutrophils",
    "Newborn",
    "Nitrogen narcosis",
    "Nocturia",
    "Noncardiogenic shock",
    "Noncompensatory pause",
    "Noncompetitive antagonism",
    "Nonconstituted drug vial/Mix-o-Vial",
    "Nonfeasance",
    "Nonmaleficence",
    "Nonverbal communication",
    "Normal flora",
    "Normal sinus rhythm",
    "Nosocomial",
    "Nosocomial infection",
    "Nuclear detonation",
    "Nucleus",
    "Obligate intracellular parasite",
    "Oblique",
    "Oblique fracture",
    "Obstetrics",
    "Obstructive shock",
    "Ocular medication",
    "Off-line medical direction",
    "Ohm",
    "Ohm's law",
    "Olecranon",
    "Oliguria",
    "Omphalocele",
    "Oncotic force",
    "On-line medical direction",
    "Onset of action",
    "Open cricothyrotomy",
    "Open fracture",
    "Open incident",
    "Open stance",
    "Open-ended questions",
    "Operations",
    "Ophthalmoscope",
    "Opportunistic pathogen",
    "Opposition",
    "Orbit",
    "Ordnance",
    "Organ",
    "Organ system",
    "Organelles",
    "Organism",
    "Organophosphates",
    "Origin",
    "Oropharyngeal airway",
    "Orthopnea",
    "Orthostatic hypotension",
    "Osmolality",
    "Osmolality",
    "Osmosis",
    "Osmotic diuresis",
    "Osmotic gradient",
    "Osmotic pressure",
    "Osteoarthritis",
    "Osteoblast",
    "Osteoclast",
    "Osteocyte",
    "Osteoporosis",
    "Otitis media",
    "Otoscope",
    "Overdrive respiration",
    "Overhydration",
    "Overpressure",
    "Over-the-needle catheter/angiocatheter",
    "Ovulation",
    "Oxidation",
    "Oxidizer",
    "Oxygen",
    "Pa",
    "Pallor",
    "Palmar grasp",
    "Palpation",
    "Pancolitis",
    "Panic attack",
    "Papilla",
    "Paradoxical breathing",
    "Parasite",
    "Parasympathetic nervous system",
    "Parasympatholytic",
    "Parasympathomimetic",
    "Parenchyma",
    "Parenteral route",
    "Parkinson's disease",
    "Paroxysmal nocturnal dyspnea (PND)",
    "Partial pressure",
    "Partial seizures",
    "Partial thickness burn",
    "Particulate evidence",
    "Partner abuse",
    "Passive immunity",
    "Passive transport",
    "Pathogen",
    "Pathology",
    "Pathophysiology",
    "Patient assessment",
    "Patient interview",
    "Peak load",
    "Pedicles",
    "PEEP",
    "Peer review",
    "Pelvic inflammatory disease (PID)",
    "Pelvic space",
    "Pelvis",
    "Penetrating trauma",
    "Penis",
    "Peptic ulcer",
    "Percussion",
    "Perforating canals",
    "Perfusion",
    "Pericardial tamponade",
    "Pericardium",
    "Perimetrium",
    "Perinephric abscess",
    "Periorbital ecchymosis",
    "Periosteum",
    "Peripheral arterial atherosclerotic disease",
    "Peripheral nervous system (PNS)",
    "Peripheral neuropathy",
    "Peripheral vascular resistance",
    "Peripheral venous access",
    "Peripherally inserted central catheter (PICC)",
    "Peristalsis",
    "Peritoneal dialysis",
    "Peritoneal space",
    "Peritoneum",
    "Peritonitis",
    "Permissive",
    "Persistent fetal circulation",
    "Personal protective equipment (PPE)",
    "Personal-care home",
    "Personality disorder",
    "Pertussis",
    "pH",
    "Phagocytes",
    "Phagocytosis",
    "Phalanges",
    "Pharmacodynamics",
    "Pharmacokinetics",
    "Pharmacology",
    "Pharyngitis",
    "Pharyngo-tracheal lumen airway (PtL)",
    "Pharynx",
    "Phobia",
    "Phototherapy",
    "Physiological stress",
    "Physiology",
    "Pia mater",
    "Pierre Robin syndrome",
    "Pill-rolling motion",
    "Pinch points",
    "Pinna",
    "Pinworm",
    "Pitting",
    "Placenta",
    "Placental barrier",
    "Planning",
    "Plasma",
    "Plasma protein systems",
    "Plasma-level profile",
    "Platelet",
    "Platelet phase",
    "Pleura",
    "Pleural friction rub",
    "Pleuritic",
    "Pluripotent stem cell",
    "Pneumatic anti-shock garment (PASG)",
    "Pneumomediastinum",
    "Pneumonia",
    "Pneumothorax",
    "Poiseuille's law",
    "Poliomyelitis (polio)",
    "Polycythemia",
    "Polypharmacy",
    "Polyuria",
    "Pons",
    "Portal",
    "Portal system",
    "Positional asphyxia",
    "Positive end-expiratory pressure (PEEP)",
    "Postpartum depression",
    "Post-conventional reasoning",
    "Posterior medial sulcus",
    "Post-ganglionic nerves",
    "Postrenal acute renal failure",
    "Posttraumatic stress syndrome",
    "Posture",
    "PPD",
    "Prearrival instructions",
    "Precordial (chest) leads",
    "Precordium",
    "Prefilled/preloaded syringe",
    "Pre-ganglionic nerves",
    "Prehospital care report (PCR)",
    "Preload",
    "Premenstrual syndrome (PMS)",
    "Prerenal acute renal failure",
    "Presbycusis",
    "Pressure ulcer",
    "Pressure wave",
    "Preventive strategy",
    "Priapism",
    "Primary area of responsibility (PAR)",
    "Primary care",
    "Primary contamination",
    "Primary immune response",
    "Primary intention",
    "Primary prevention",
    "Primary problem",
    "Primary response",
    "Primary triage",
    "Prinzmetal's angina",
    "Prions",
    "priority dispatching",
    "Proctitis",
    "prodrug (parent drug)",
    "Profession",
    "Professionalism",
    "Profile",
    "Prognosis",
    "prolonged QT interval",
    "prompt care facilities",
    "Prostaglandins",
    "Prostate",
    "Prostatitis",
    "Protocols",
    "Prototype",
    "Protozoan",
    "proximal tubule",
    "proximate cause",
    "Pruritus",
    "PSAP",
    "pseudo-instinctive",
    "psychogenic amnesia",
    "psychoneuroimmunological regulation",
    "Psychosis",
    "Psychosocial",
    "psychotherapeutic medication",
    "Pubis",
    "Puerperium",
    "pulmonary agents",
    "pulmonary embolism (PE)",
    "pulmonary hilum",
    "pulmonary over-pressure",
    "pulse oximeter",
    "pulse oximetry",
    "pulse pressure",
    "pulse quality",
    "pulse rate",
    "pulse rhythm",
    "pulsus paradoxus",
    "Puncture",
    "Pupil",
    "Pus",
    "Pyelonephritis",
    "Pyramid",
    "Pyrexia",
    "Pyrogen",
    "QRS axis",
    "QT interval",
    "quality assurance (QA)",
    "quality improvement (QI)",
    "quality of respiration",
    "Rabies",
    "Rad",
    "Radiation",
    "radio band",
    "radio frequency",
    "Radius",
    "Rape",
    "Rapid Intervention Team",
    "rapid sequence intubation",
    "rapid trauma assessment",
    "Reabsorption",
    "reasonable force",
    "rebound tenderness",
    "Receptor",
    "Reciprocal",
    "Reciprocity",
    "recirculating currents",
    "Recompression",
    "red bone marrow",
    "reduced nephron mass",
    "reduced renal mass",
    "Reduction",
    "referred pain",
    "Reflective",
    "refractory period",
    "Regeneration",
    "Registration",
    "relative refractory period",
    "Remodeling",
    "Renal",
    "renal ARF (renal acute renal failure)",
    "renal calculi",
    "renal dialysis",
    "renal pelvis",
    "Renin",
    "Repair",
    "Repolarization",
    "reportable collisions",
    "res ipsa loquitur",
    "reserve capacity",
    "Reservoir",
    "Resiliency",
    "Resistance",
    "Resolution",
    "resolution phase",
    "Respiration",
    "Respirator",
    "respiratory acidosis",
    "respiratory alkalosis",
    "respiratory effort",
    "respiratory rate",
    "respiratory shock",
    "respiratory syncytial virus (RSV)",
    "response time",
    "resting potential",
    "reticular activating system",
    "reticuloendothelial system (RES)",
    "Retina",
    "retinal detachment",
    "Retinopathy",
    "retroauricular ecchymosis",
    "retrograde amnesia",
    "retroperitoneal space",
    "return of spontaneous circulation (ROSC)",
    "review of systems",
    "Rh blood group",
    "Rh factor",
    "Rhabdomyolysis",
    "rheumatoid arthritis",
    "Rhinorrhea",
    "Rhonchi",
    "rhythm strip",
    "right axis deviation",
    "rooting reflex",
    "Rouleaux",
    "rubella (German measles)",
    "rule of nines",
    "rule of palms",
    "rules of evidence",
    "rust out",
    "Ryan White Act",
    "Safety Officer (SO)",
    "saline lock",
    "scabies",
    "Scaffolding",
    "Scapula",
    "scene safety",
    "scene-authority law",
    "Schizophrenia",
    "Sclera",
    "scope of practice",
    "Scrambling",
    "Scree",
    "Scrotum",
    "Scuba",
    "sebaceous glands",
    "Sebum",
    "second messenger",
    "secondary contamination",
    "secondary immune response",
    "secondary intention",
    "secondary prevention",
    "secondary response",
    "secondary triage",
    "Secretion",
    "secretory immune system",
    "Section Chief",
    "Sector",
    "secure attachment",
    "Sedation",
    "Seizure",
    "Sellick maneuver",
    "Semantic",
    "Semen",
    "semicircular canals",
    "semi-Fowler's position",
    "Semipermeable",
    "Sengstaken-Blakemore tube",
    "senile dementia",
    "Sensitization",
    "sensorineural deafness",
    "Sensorium",
    "septic shock",
    "Septicemia",
    "Septum",
    "Sequestration",
    "Seroconversion",
    "Serotonin",
    "serous fluid",
    "Serum",
    "sesamoid bone",
    "severe acute respiratory syndrome (SARS)",
    "sexual assault",
    "sexually transmitted disease (STD)",
    "sharps container",
    "shear points",
    "shipping papes",
    "Shock",
    "short haul",
    "Shunt",
    "Shy-Drager syndrome",
    "sick sinus syndrome",
    "sickle cell anemia",
    "side effect",
    "silent myocardial infarction",
    "silo gas",
    "simple diffusion",
    "simple partial seizure",
    "Simplex",
    "singular command",
    "Sinus",
    "Sinusitis",
    "Slander",
    "slow-reacting substance of anaphylaxis (SRS-A)",
    "slow-to-warm-up child",
    "Sociocultural",
    "Solvent",
    "somatic nervous system",
    "somatic pain",
    "somatoform disorder",
    "span of control",
    "Spasm",
    "Special Weapons and Tactics (SWAT) Team",
    "specific gravity",
    "sperm cell",
    "Sphygmomanometer",
    "Spike",
    "spina bifida (SB)",
    "spinal canal",
    "spinal cord",
    "spinal nerves",
    "spinous process",
    "spiral fracture",
    "Spondylosis",
    "spontaneous pneumothorax",
    "Spotter",
    "Sprain",
    "Staff Functions",
    "Staging area",
    "Staging Officer",
    "standard of care",
    "standing orders",
    "Starling's law of the heart",
    "START",
    "status epilepticus",
    "stem cells",
    "Stenosis",
    "Sterile",
    "Sterilize",
    "Sterilizing",
    "Stethoscope",
    "stock solution",
    "Stokes-Adams syndrome",
    "Stoma",
    "Strain",
    "Strainers",
    "Stress",
    "stress response",
    "Stressor",
    "Stridor",
    "Stroke",
    "stroke volume",
    "Stylet",
    "subarachnoid hemorrhage",
    "Subcutaneous",
    "subcutaneous emphysema",
    "subcutaneous tissue",
    "subdural hematoma",
    "subendocardial infarction",
    "Subglottic",
    "Sublingual",
    "Subluxation",
    "substance abuse",
    "sucking reflex",
    "Suction",
    "sudden death",
    "sudden infant death syndrome (SIDS)",
    "sudoriferous glands",
    "superficial burn",
    "superficial frostbite",
    "supine hypotensive syndrome",
    "Suppository",
    "Supraglottic",
    "surface absorption",
    "Surfactant",
    "Survival",
    "Sutures",
    "sympathetic nervous system",
    "Sympatholytic",
    "Sympathomimetic",
    "Synapse",
    "Synarthrosis",
    "synchronized cardioversion",
    "Syncope",
    "Syncytium",
    "Synergism",
    "synovial fluid",
    "synovial joint",
    "Syphilis",
    "Syringe",
    "system status management (SSM)",
    "Systemic",
    "systemic effects",
    "Systole",
    "systolic blood pressure",
    "T cell receptor (TCR)",
    "T lymphocytes",
    "Tachycardia",
    "Tachypnea",
    "Tactical Emergency Medical Services (TEMS)",
    "tactile fremitus",
    "teachable moments",
    "Tenderness",
    "Tendonitis",
    "Tendons",
    "tension lines",
    "tension pneumothorax",
    "teratogenic drug",
    "terminal-drop hypothesis",
    "termination of action",
    "terrorist act",
    "tertiary prevention",
    "Testes",
    "Tetanus",
    "Thalamus",
    "therapeutic index",
    "therapy regulator",
    "thermal gradient",
    "Thermogenesis",
    "Thermoregulation",
    "thoracoabdominal pump",
    "Thrill",
    "Thrombocytes",
    "Thrombocytopenia",
    "Thrombocytosis",
    "Thrombophlebitis",
    "Thrombosis",
    "Thrombus",
    "thyrotoxic crisis",
    "Thyrotoxicosis",
    "Tibia",
    "tidal volume",
    "tiered response system",
    "tilt test",
    "Tinnitus",
    "Tissue",
    "Tocolysis",
    "Tolerance",
    "Tone",
    "tonic phase",
    "tonic-clonic seizure",
    "Tonicity",
    "topical medications",
    "Tort",
    "total body water (TBW)",
    "total down time",
    "total lung capacity",
    "touch pad",
    "Tourniquet",
    "Toxicology",
    "Toxidrome",
    "Toxin",
    "Trachea",
    "tracheal deviation",
    "tracheal tugging",
    "tracheobronchial tree",
    "Tracheostomy",
    "Trajectory",
    "Transection",
    "transient ischemic attack (TIA)",
    "transmural infarction",
    "Transportation Unit Supervisor",
    "transverse fracture",
    "transverse process",
    "Trauma",
    "trauma center",
    "trauma registry",
    "trauma triage criteria",
    "Treatment Group Supervisor",
    "Treatment Unit Leaders",
    "trench foot",
    "Triage",
    "Triage Group Supervisor",
    "Triage officer",
    "triage tags",
    "trichinosis",
    "Trichomoniasis",
    "Trocar",
    "Trunking",
    ".",
    "tuberculosis (TB)",
    "tunica adventitia",
    "tunica intima",
    "tunica media",
    "Turgor",
    "Turnover",
    "two-pillow orthopnea",
    "Ulna",
    "ultrahigh frequency",
    "umbilical cord",
    "UN number",
    "unified command",
    "unipolar limb leads",
    "Unit",
    "upper airway obstruction",
    "upper gastrointestinal bleeding",
    "up-regulation",
    "Urea",
    "Uremia",
    "Ureter",
    "Urethra",
    "Urethritis",
    "urinary bladder",
    "urinary stasis",
    "urinary system",
    "urinary tract infection (UTI)",
    "Urine",
    "Urology",
    "Urosepsis",
    "Urostomy",
    "Urticarial",
    "Vaccine",
    "Vacutainer",
    "vagal response",
    "vagus nerve",
    "Vallecular",
    "valsalva maneuver",
    "Varicella",
    "varicose veins",
    "Varicosities",
    "vas deferens",
    "vascular phase",
    "Vasculitis",
    "vasomotor center",
    "Vector",
    "Vein",
    "Velocity",
    "venous access device",
    "venous constricting band",
    "ventilation",
    "ventricular filling",
    "Venturi mask",
    "Vertebra",
    "vertebral body",
    "Vertigo",
    "very high frequency",
    "vesicants",
    "Vial",
    "Virulence",
    "Virus",
    "visceral pain",
    "visual acuity wall chart/card",
    "vital statistics",
    "vitreous humor",
    "Volatility",
    "Voltage",
    "volume on hand",
    "Volvulus",
    "von Willebrand's disease",
    "warm zone",
    "warning placard",
    "Washout",
    "weapons of mass destruction (WMD)",
    "Wernicke's syndrome",
    "Wheezes",
    "white matter",
    "whole bowel irrigation",
    "window phase",
    "windshield survey",
    "Withdrawal",
    "wrap points",
    "xiphisternal joint",
    "Yaw",
    "years of productive life",
    "yellow bone marrow",
    "Zollinger-Ellison syndrome",
    "zone of coagulation",
    "zone of hyperemia",
    "zone of stasis",
    "Zygoma"
  ];


const resultbox=document.querySelector(".resultbox")
const inputbox=document.querySelector("#search")
var searchbtn=document.querySelector('#searchicon')

inputbox.onkeyup=function(){
    let result=[];
    let input=inputbox.value
    if(input.length){
        result=words.filter((e)=>{
            return e.toLowerCase().startsWith(input.toLowerCase());
        });

    }
    
    if(result.length===0){
        resultbox.innerHTML = input.length === 0 ? '' : '<ul><li>No results found</li></ul>';
        searchbtn.addEventListener('click',function(e){
            resultbox.innerHTML='';
        })
    }
    else{
        display(result);
    }
}

// inputbox.addEventListener("focus",function(){})

function display(result){
    const content =result.map((list)=>{
        return "<li onclick=selectinput(this)>" +list +"</li>";
    }).join('')
    resultbox.innerHTML="<ul>" + content+ "</ul>"
}

function selectinput(list){
    inputbox.value=list.innerHTML
    resultbox.innerHTML='';
    search();
}